name: Build Studio Tools

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Create Python virtual environment
        run: python -m venv .venv

      - name: Verify Python (venv)
        run: |
          .venv/bin/python --version
        if: runner.os != 'Windows'

      - name: Verify Python (venv, Windows)
        if: runner.os == 'Windows'
        run: .venv\Scripts\python --version
        shell: cmd


      # Linux + macOS
      - name: Run launch script (Unix)
        if: runner.os != 'Windows'
        run: |
          chmod +x ./launch.sh
          source .venv/bin/activate
          ./launch.sh
        shell: bash

      # Windows
      - name: Run launch script (Windows)
        if: runner.os == 'Windows'
        run: |
          call .venv\Scripts\activate
          launch.bat
        shell: cmd
