name: Build Studio Tools

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install X11 dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libxt-dev \
            libgl1-mesa-dev \
            mesa-common-dev \
            libglu1-mesa-dev \
            libglvnd-dev

      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Create Python virtual environment
        run: python -m venv .venv

      - name: Add venv to PATH
        if: runner.os != 'Windows'
        run: echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Add venv to PATH (Windows)
        if: runner.os == 'Windows'
        run: echo %GITHUB_WORKSPACE%\.venv\Scripts>> %GITHUB_PATH%
        shell: cmd


      - name: Install Pre-Requesists (venv)
        run: |
          .venv/bin/python -m pip install -r ./requirements.txt
        if: runner.os != 'Windows'

      - name: Install Pre-Requesists (venv, Windows)
        if: runner.os == 'Windows'
        run: .venv\Scripts\python -m pip install -r ./requirements.txt
        shell: cmd

      - name: Create USD directory
        run: mkdir usd

      - name: Clone OpenUSD
        run: git clone https://github.com/PixarAnimationStudios/OpenUSD.git usd/source

      - name: Build OpenUSD (venv)
        if: runner.os != 'Windows'
        run: |
          .venv/bin/python ./usd/source/build_scripts/build_usd.py ./usd/install
        shell: bash
        
      - name: Build OpenUSD (venv, Windows)
        if: runner.os == 'Windows'
        run: |
          .venv\Scripts\python ./usd/source/build_scripts/build_usd.py ./usd/install
        shell: cmd

      # Linux + macOS
      - name: Run launch script (Unix)
        if: runner.os != 'Windows'
        run: |
          chmod +x ./launch.sh
          ./launch.sh
        shell: bash

      # Windows
      - name: Run launch script (Windows)
        if: runner.os == 'Windows'
        run: |
          launch.bat
        shell: cmd
